### ISSUE TITLE
move to new release cycle

### ISSUE THREAD

**Issue by kordano** [replikativ/konserve#69]
With the new release strategy on Datahike, we also need a rolling release on konserve. 

@jsmassa What issues are still open with the creation of the new `main` branch out of `develop`and the integration of the `master` branch?

@whilo What parts of the `master` branch are necessary for a release?

**Comment by jsmassa** [comment]
1) The `main` branch has been created and is only missing the **new CI pipeline**. I have consciously refrained from doing that just yet to not produce releases before the branch is ready.
2) Since the **master** branch has commits that are not in the development branch, I do not know if there is something in there we should keep.
3) There were problems that occurred while checking the tests:
- `./bin/kaocha`: Updating the `incognito` library to `0.2.7` gives `Could not find artifact com.cognitect:fress:jar:0.3.1 in central (https://repo1.maven.org/maven2/)`
- `./bin/run-cljstests`:  The warning `Use of undeclared Var clojure.core.async/<!` occurs originating from `superv/async.cljc:557:3`
  Regarding ClojureScript the use of `karma` also needs to be checked as the version being used is far behind and `karma-cljs-test` has never been updated.

**Comment by RokLenarcic** [comment]
CLJS is broken and any app attempting to use this version of Konserve will be met with:
```
[:main] Compiling ...
[:main] Build failure:
The required namespace "incognito.fressian" is not available, it was required by "konserve/serializers.cljc".
"incognito/fressian.clj" was found on the classpath. Maybe this library only supports CLJ?
```

**Comment by TimoKramer** [comment]
@RokLenarcic can you please open a new issue with your problem, this does not really fit this one. And we will need a bit more information on your problem as well, especially which version you are using.

**Comment by jsmassa** [comment]
Update:
1. Still has to be done. Probably easiest later to look at [incognito](https://github.com/replikativ/incognito) later for this.
2. I have looked at the commits from master now and cherry-picked or redone everything that was changed in code, which was to add type hints.
3. As soon as the [incognito issue](https://github.com/replikativ/incognito/issues/10) is fixed, we can update the dependency version. [Superv.async](https://github.com/replikativ/superv.async) is also being updated at this moment.

**Comment by kordano** [comment]
Ok, and where possible please update the build tools in your new [main branch](https://github.com/replikativ/konserve/tree/main) so we would have a consistent tooling around that. As discussed with @TimoKramer we would move everything to a build file like in my upcoming [incognito](https://github.com/replikativ/incognito/blob/migrate-release-cycle/build.clj) release.
