### ISSUE TITLE
custom Fressian handlers

### ISSUE THREAD

**Issue by danielsz** [replikativ/konserve#7]
Hello @whilo , 

I was scratching my head regarding how to best de/serialize unknown types .

Trying to store a `org.joda.time.DateTime`, for example, will result in a Write error. 

I am not clear to what extent the `Incognito` readers and writers are supposed to adapt automatically regarding unknown types. 

I am also not clear how to pass along custom Fressian handlers and where the integration points are. 

Thank you.

**Comment by whilo** [comment]
`incognito` can adapt to Clojure types which `pr-str` to something readable. This is not the case for general Java objects like `org.joda.time.DateTime`. For this case you would provide an `incognito` write-handler to return a readable Clojure representation of it. I can provide an example handler code, I am just on holidays, but feel free to ping back if you have any troubles and I will help out.

**Comment by whilo** [comment]
Has it worked out for you? I can provide an example if not. Incognito just provides protocols for all kind of different serialization protocols for Clojure, so they become pluggable.

**Comment by danielsz** [comment]
Hi, 

Thank you for following up on this. I haven't sweated much on this and moved on, but the moment you mention providing an example, I'm going all, like, yeah, that would be nice, thank you so much for the offer. That would definitely help shorten the path to Satori and bliss :-)

**Comment by danielsz** [comment]
Hi @whilo, 

Getting closer. 

I have defined a fressian custom [handler](https://github.com/danielsz/maarschalk/blob/e6f70ded4de88d824dd77ecd53ae6aa37dd0a642/src/maarschalk/fressian.clj
) for JodaTime, and I have a passing [test](https://github.com/danielsz/maarschalk/blob/e6f70ded4de88d824dd77ecd53ae6aa37dd0a642/test/maarschalk/fressian_test.clj).

All I'm missing now is the way to hook it up in the incognito machinery. 

Your help will be very much appreciated.

**Comment by whilo** [comment]
Nice! I have some code partially working, but now I realize that this does not fit the incognito model of hijacking the map-type for Clojure, because the Joda DateTime is a totally custom type. In general I am not very happy with incognito, I just wrote it so that custom record types do not get lost on serialization. Is this a problem for you? Records will become plain maps otherwise. In a distributed system this is somewhat bad (you silently lose information), but I am not sure how to hook into the Clojure infrastructure to retain the record information.

I would expose the handler's for the fressian serializer here: https://github.com/replikativ/konserve/blob/master/src/konserve/serializers.cljc#L18 So you will have to deal with the serializer directly again and not have one general incognito one... I would drop incognito then and just expose the handlers for each serializer directly then. This puts the burden of custom serialization again on the user of konserve.

**Comment by danielsz** [comment]
Thank you, @whilo, I got it working. 

With the current state, I had to write my own instance of FressianSerializer, but I'm proposing a PR to allow passing custom handlers to the existing implementation.

**Comment by whilo** [comment]
Thanks a lot, I have decide to merge it for now, as I don't see a simpler solution.
